weights: /content/drive/MyDrive/MicroIntelligence/shapes_dataset_v2/weights/YOLOv5_DOTAv1.5_OBB.pt
cfg: /content/YOLOv5_DOTA_OBB/models/yolov5m.yaml
data: /content/YOLOv5_DOTA_OBB/data/DOTA_ROTATED.yaml
hyp: /content/YOLOv5_DOTA_OBB/data/hyp.finetune.yaml
epochs: 300
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: true
noautoanchor: true
evolve: false
bucket: ''
cache_images: true
image_weights: false
name: first_trial
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 32
world_size: 1
global_rank: -1
