weights: rotate-yolov5s-ucas.pt
cfg: /content/RotateObjectDetection/rotate-yolov5/models/rotate_yolov5s_ucas.yaml
data: /content/RotateObjectDetection/rotate-yolov5/data/rotate_ucas.yaml
hyp: /content/RotateObjectDetection/rotate-yolov5/data/hyp.ucas.yaml
epochs: 200
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: true
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: trial_02
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
rotate: true
world_size: 1
global_rank: -1
save_dir: runs/train/trial_022
total_batch_size: 32
